# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_findpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=1, verbose_name='个人描述'),
            preserve_default=False,
        ),
    ]
