# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 14:21
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator_sor',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='avator/default.jpg', upload_to='avator/%Y%m%d/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='个人描述'),
        ),
    ]
