# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 02:21
from __future__ import unicode_literals

import apps.exercise.validator
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.IntegerField(choices=[(1, '肩膀'), (2, '手臂'), (3, '胸部'), (4, '背部'), (5, '腰部'), (6, '腿部')], null=True, validators=[apps.exercise.validator.valid_difficulty], verbose_name='部位选择')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='详情')),
                ('pub_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='入库时间')),
                ('status', models.BooleanField(default=False, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '健身部位',
                'verbose_name_plural': '健身部位',
                'permissions': (('can_change_question', '可以修改题目信息'), ('can_add_question', '可以添加题目信息'), ('can_change_question_status', '可以修改题目状态')),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='actions',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.Category', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='actions',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='贡献者'),
        ),
        migrations.AddField(
            model_name='actions',
            name='tag',
            field=models.ManyToManyField(to='exercise.Tag', verbose_name='部位标签'),
        ),
    ]
