# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoulder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='标题')),
                ('pic', models.ImageField(default='media/avator/default.jpg', upload_to='', verbose_name='图片')),
                ('outline', models.TextField(verbose_name='概要')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '身体部位',
                'verbose_name_plural': '身体部位',
            },
        ),
    ]
