# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-28 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_shoulder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoulder',
            name='content',
        ),
        migrations.RemoveField(
            model_name='shoulder',
            name='outline',
        ),
    ]
