# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-31 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_auto_20190828_2212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoulder',
            new_name='Part',
        ),
    ]
