# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-31 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20190831_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='pic',
            field=models.ImageField(upload_to='', verbose_name='图片'),
        ),
    ]
